### PR TITLE
Complete rewrite of the beaconmaster script.

### PR DESCRIPTION
**Pull request by TomBayne**
Aiming to use a proper object oriented approach, with a modular design that can be expanded upon in the future.

This was something I threw together in an hour tonight as I was bored, hopefully it should work. I've unfortunately not got a device to test this code on, but all of the commands sent to the device are the same as your original code, so there's no reason why it wouldn't work :)

Let me know if you get any errors and I'll try to resolve them :)

### CODE REVIEW

**Comment by andymux** [comment]
Wow! This looks great, looks way better than my chatGPT cobble 🤣

I'll give it a test run ASAP!

Thanks for your help on this!

**Comment by TomBayne** [comment]
Rewrote the other files too.

**Comment by TomBayne** [comment]
Tbh this is still not well designed. In theory we should abstract the program into the following independent modules:

- A file which describes the Serial Connection object
- A file which describes how messages are sent via that connection object
- A file which describes the User Interface
- A file which describes the required messages to act as a specific role (messenger, repeater, etc)

This way each 'function' is independent, and can be worked on individually from other functionality of the software.
There is potentially ways to even further abstract each part of the functionality of the software, but these are my preliminary thoughts.

**Comment by TomBayne** [comment]
Closing this PR for now as I work on my own fork. I'll create a new PR when more progress is made.
Things are going well so far 🎉

**Pull request closed without merging**
